kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: experiment4
  namespace: chaos-testing-netem
#  annotations:
#    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '@every 15s'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: NetworkChaos
  networkChaos:
    selector:
      namespaces:
        - squidgame
      labelSelectors:
        app: myapp
    mode: one
    action: delay
    delay:
      latency: '10ms'
      correlation: '100'
      jitter: '0ms'
    duration: 5m
